version: '3.5'
services:
  fluentd:
    build: ./fluentd-audit
    container_name: fluentd
    volumes:
    - ./env/fluentd/etc:/fluentd/etc
    ports:
    - "24224:24224"
    - "24224:24224/udp"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.1
    container_name: elasticsearch
    ports:
    - "9200:9200"
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.1
    container_name: kibana
    ports:
    - "5601:5601"
  keycloak:
    build: ./keycloak-audit
    container_name: keycloak
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - FLUENT_HOST=fluentd
    command:
    - "-b 0.0.0.0"
    - "-Dkeycloak.import=/opt/jboss/keycloak/audit-realm.json"
    ports:
    - "8080:8080"
    volumes:
    - ./env/keycloak/audit-realm.json:/opt/jboss/keycloak/audit-realm.json