version: '2'
services:
  fluentd:
    image: novomatic/fluentd-elasticsearch:v1.1-debian
    volumes:
    - ./env/fluentd/etc:/fluentd/etc
    links:
    - "elasticsearch"
    ports:
    - "24224:24224"
    - "24224:24224/udp"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.1
    expose:
    - 9200
    ports:
    - "9200:9200"
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.1
    links:
    - "elasticsearch"
    ports:
    - "5601:5601"
  keycloak:
    build: ./keycloak-audit
    expose:
    - 8080
    environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - FLUENT_HOST=fluentd
    command:
    - "-b 0.0.0.0"
    - "-Dkeycloak.import=/opt/jboss/keycloak/audit-realm.json"
    ports:
    - "8080:8080"
    volumes:
    - ./env/keycloak/audit-realm.json:/opt/jboss/keycloak/audit-realm.json