{
 "title": "Keycloak",
 "description": "Dashboard for Keycloak metrics",
 "tags": [
  "keycloak",
  "IAM"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_bytes_used", "legendFormat": "{{area}} memory" }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_current", "legendFormat": "current" },
    { "expr": "jvm_threads_daemon", "legendFormat": "daemon" }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_classes_loaded", "legendFormat": "loaded" }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}