{
 "title": "Web app",
 "description": "Dashboard for web application",
 "tags": [
  "node.js",
  "hapijs"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "path",
    "label": "Path",
    "query": "label_values(http_request_duration_seconds_count, path)"
   },
   {
    "name": "status_code",
    "label": "Status Code",
    "query": "label_values(http_request_duration_seconds_count{path=~\"$path\"}, status_code)"
   }
  ]
 },
 "panels": [
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[30s])*100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Total Allocated Heap Size (bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes",
     "legendFormat": "Heap Size Allocated {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Usage From Total Allocated (bytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes", "legendFormat": "Heap Size Used {{instance}}" }
   ]
  },
  {
   "title": "API Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average request duration [30s]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(http_request_duration_seconds_count{path=~\"$path\", status_code=~\"$status_code\"}[30s])",
       "legendFormat": "{{path}} [{{status_code}}]"
      }
     ]
    },
    {
     "title": "Status Code Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_seconds_count{status_code=~\"$status_code\", path=~\"$path\"}[1m])) / sum(rate(http_request_duration_seconds_count{path=~\"$path\"}[1m]))",
       "legendFormat": "$status_code rate"
      }
     ]
    },
    {
     "title": "Request latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{path=~\"$path\", status_code=~\"$status_code\"}[1m])) by (le))",
       "legendFormat": "Request latency - 90th percentile"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{path=~\"$path\", status_code=~\"$status_code\"}[1m])) by (le))",
       "legendFormat": "Request latency - 95th percentile"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{route=~\"$path\", status_code=~\"$status_code\"}[1m])) by (le))",
       "legendFormat": "Request latency - 99th percentile"
      }
     ]
    }
   ]
  }
 ]
}