global:
  scrape_interval:     15s
  evaluation_interval: 15s


scrape_configs:

- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'docker'
  scrape_interval: 5s
  static_configs:
  - targets: ['host.docker.internal:9323']

- job_name: 'elasticsearch_exporter'
  scrape_interval: 5s
  static_configs:
  - targets: ['elasticsearch_exporter:9108']