global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: keycloak
    static_configs:
      - targets:
        - keycloak:5555
  - job_name: web-app
    static_configs:
      - targets:
        - web-app:3030
  - job_name: elasticsearch
    static_configs:
      - targets:
         - elasticsearch-exporter:9108
  - job_name: kibana
    metrics_path: /_prometheus/metrics
    static_configs:
      - targets:
          - kibana:5601